language: php

php:
  - 7.0

sudo: false

install:
  - bash install_phalcon.sh 3.4.2
  - composer update --dev --quiet

script:
  - php vendor/bin/codecept run unit --coverage --coverage-xml
  - php vendor/bin/phpcs src/ --standard=psr2
  - php vendor/bin/phpcs tests/unit/ --standard=psr2

after_script:
  - mkdir -p build/logs
  - mv tests/_output/coverage.xml build/logs/clover.xml
  - php vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: 558a4a5108bf15fedffb7884bc47fae17ae2fcb7db7e4a5de8a4f5ff22858938

notifications:
  email:
    - sid@sidroberts.co.uk
