language: php

php:
  - 7.0

sudo: true

env:
  - PHALCON_VERSION="v3.4.1"

git:
  depth: 1

install:
  - composer self-update
  - git clone --depth=1 -q --branch=${PHALCON_VERSION} https://github.com/phalcon/cphalcon.git
  - '(cd cphalcon/build; bash install &>/dev/null && phpenv config-add ../tests/_ci/phalcon.ini &> /dev/null && cd ../..;)'
  - php --ri phalcon
  - composer update --dev --no-interaction

script:
  - php vendor/bin/codecept run unit --coverage --coverage-xml
  - php vendor/bin/phpcs src/ --standard=psr2
  - php vendor/bin/phpcs tests/unit/ --standard=psr2

after_script:
  - mkdir -p build/logs
  - mv tests/_output/coverage.xml build/logs/clover.xml
  - php vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: 558a4a5108bf15fedffb7884bc47fae17ae2fcb7db7e4a5de8a4f5ff22858938

notifications:
  email:
    - sid@sidroberts.co.uk
