language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

os:   linux
dist: xenial

env:
  - PSR_VERSION="1.0.0" PHALCON_VERSION="4.0.5"

git:
  depth: 1

install:
  - pecl install --force psr-$PSR_VERSION 1> /dev/null
  - pecl install --force phalcon-$PSR_VERSION 1> /dev/null
  - travis_retry composer update --no-interaction --no-progress

script:
  - vendor/bin/codecept run
  - vendor/bin/phpcs src/ --standard=psr2

notifications:
  email:
    - sid@sidroberts.co.uk
